## src/tests/FractionTests/BUILD

cc_library(
    name = "FractionTests",
    srcs = ["FractionTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Fraction:Fraction",
    ]
)
